### ISSUE TITLE
pip install doesn't find package

### ISSUE THREAD

**Issue by ferdinandyb** [anntzer/mplterm#2]
`python -m pip install mplterm` does not find this package. I'm guessing it is not on pypi? If so you might want to update the README with a copyable command instead of "Install with [pip](https://pip.pypa.io/), as any Python package." I'd probably also throw in usage via `matplotlib.use("module://mplterm")`

**Comment by anntzer** [comment]
Thanks for the suggestions, I updated the readme accordingly.
