### ISSUE TITLE
Doesn't seem to work inside tmux.

### ISSUE THREAD

**Issue by ferdinandyb** [anntzer/mplterm#3]
Note, that for sixel support in tmux you need you'll need at least https://github.com/tmux/tmux/commit/1a1290f30b21bcc07e64eb7cb837a3c522779685, but probably https://github.com/tmux/tmux/commit/f68d35c52962c095e81db0de28219529fd6f355e is safer.

Running `MPLTERM=protocol=sixel ipython` and then trying to call `plt.show()` in tmux results in the terminal becoming cleared and mplterm hanging here:
```
File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/matplotlib/pyplot.py:446, in show(*args, **kwargs)
    402 """
    403 Display all open figures.
    404
   (...)
    443 explicitly there.
    444 """
    445 _warn_if_gui_out_of_main_thread()
--> 446 return _get_backend_mod().show(*args, **kwargs)

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/matplotlib/backend_bases.py:2894, in FigureManagerBase.pyplot_show(cls, block)
   2892 for manager in managers:
   2893     try:
-> 2894         manager.show()  # Emits a warning for non-interactive backend.
   2895     except NonGuiException as exc:
   2896         _api.warn_external(str(exc))

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/mplterm/__init__.py:101, in _MpltermFigureManager.show(self)
     99 fig = self.canvas.figure
    100 with ExitStack() as stack:
--> 101     size = proto.get_pixel_size()
    102     if size is not None:
    103         stack.enter_context(_shrinked(fig, size))

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/mplterm/_sixel.py:42, in Sixel.get_pixel_size()
     40 @staticmethod
     41 def get_pixel_size():  # XTWINOPS
---> 42     reply = _term_query(_csi("14t"), _csi_regex(r"4;(\d+);(\d+)t"))
     43     h, w = map(int, reply)
     44     return w, h

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/mplterm/_util.py:48, in _term_query(cmd, pattern)
     46 buf = b""
     47 while True:
---> 48     buf += sys.stdin.buffer.read(1)
     49     match = regex.fullmatch(buf)
     50     if match:

KeyboardInterrupt:
```

Works like a charm outside tmux.

**Comment by anntzer** [comment]
tmux gets stuck because it does not seem to support (AFAICT) XTSMGRAPHICS and XTWINOPS (https://invisible-island.net/xterm/ctlseqs/ctlseqs.html) to query the number of color registers and the window (pane?) size in pixels; see also https://github.com/wez/wezterm/issues/609 re: the need for XTSMGRAPHICS for sixel support.

However even if I bypass these queries (and hard-code some reasonable values), tmux (installed from git HEAD) doesn't hang anymore but I still don't manage to get sixel showing; in fact even something as simple as `python -c 'from pylab import *; plot(); savefig("/tmp/test.png")'; convert /tmp/test.png -colors 256 sixel:-` gives no output for me in tmux (whereas it works fine outside of it).  Does such a command (which is close to what mplterm is basically doing) work for you?

-----

Edit: I figured out I had to build tmux with --enable-sixel; now things work if you force _getset_max_color_registers to directly return e.g. 256 and Sixel.get_pixel_size to directly return None.  I guess it would still be better if tmux supported them (I'll let you report these to tmux if you're interested).

From a quick look I guess it would also be useful (for robustness) if we could query the value of INPUT_BUF_LIMIT?

**Comment by ferdinandyb** [comment]
@anntzer Ah yes, sorry, I should've mentioned the flag. To be honest, my technical knowledge on these things is extremely limited, so although I can certainly report (and link back here), you'd probably be more convincing. Still, if you'd rather I do it, I'll do it :)

The INPUT_BUF_LIMIT is basically the largest sized sixel tmux will be able to render? Because in that case, yes, I guess that would be useful, yes.

**Comment by anntzer** [comment]
> Ah yes, sorry, I should've mentioned the flag.

No worries!

> To be honest, my technical knowledge on these things is extremely limited, so although I can certainly report (and link back here), you'd probably be more convincing. Still, if you'd rather I do it, I'll do it :)

I don't know much more -- I've only read the paragraphs about XTWINOPS and XTSMGRAPHICS in the page linked above, and they're basically ways to query the pixel size and the number of colors supported by the terminal (which are useful for sixel output for obvious reasons) -- and you seem to have more interest than I do in getting this to work in tmux (I can try to make whatever changes are reasonable in mplterm, but I don't really want to get bogged down in a discussion about tmux internals), so go for it ;) 

> The INPUT_BUF_LIMIT is basically the largest sized sixel tmux will be able to render?

If I understand the following comment https://github.com/tmux/tmux/issues/3668#issuecomment-1689540241 correctly, yes.

**Comment by ferdinandyb** [comment]
Ok, so @nicm provided a patch on the linked issue adding these. Now I get a different error:

```
_TermError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 plt.show()

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/matplotlib/pyplot.py:446, in show(*args, **kwargs)
    402 """
    403 Display all open figures.
    404
   (...)
    443 explicitly there.
    444 """
    445 _warn_if_gui_out_of_main_thread()
--> 446 return _get_backend_mod().show(*args, **kwargs)

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/matplotlib/backend_bases.py:2894, in FigureManagerBase.pyplot_show(cls, block)
   2892 for manager in managers:
   2893     try:
-> 2894         manager.show()  # Emits a warning for non-interactive backend.
   2895     except NonGuiException as exc:
   2896         _api.warn_external(str(exc))

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/mplterm/__init__.py:110, in _MpltermFigureManager.show(self)
    108 if _OPTIONS["revvideo"]:
    109     mem = _revvideo(mem)
--> 110 proto.display(mem)

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/mplterm/_sixel.py:49, in Sixel.display(mem)
     46 @staticmethod
     47 def display(mem):
     48     h, w, _ = mem.shape
---> 49     ncolors = _getset_max_color_registers()
     50     args = [
     51         "convert",
     52         "-size", f"{w}x{h}", "-depth", "8", "rgba:-",
     53         "-colors", f"{ncolors}", "sixel:-",
     54     ]
     55     with Popen(args, stdin=PIPE) as proc:

File ~/.pyenv/versions/3.11.1/lib/python3.11/site-packages/mplterm/_sixel.py:20, in _getset_max_color_registers()
     17 err, num = _term_query(
     18     _csi("?1;3;%sS" % num), _csi_regex(r"\?1;(\d);(\d+)S"))
     19 if err != "0":
---> 20     raise _TermError
     21 return int(num)

_TermError:
```

**Comment by ferdinandyb** [comment]
I should probably learn how to do these csi things ...

**Comment by anntzer** [comment]
Can you just patch mplterm to print out err, num at that line?

**Comment by ferdinandyb** [comment]
Oh, yeah sure, should have been thinking :D 
```
print(err,num)
3 1024
```

**Comment by anntzer** [comment]
Sure, I just patched mplterm to be more lenient there.

**Comment by ferdinandyb** [comment]
Oh, yeah!

![image](https://github.com/anntzer/mplterm/assets/6343487/3d6026b5-8e18-4e59-a87e-2aca5134c583)

Out of curiosity, what does `err` mean here, that you could be more lenient (I was surprised it was not a binary value also)?

Otherwise, thanks very much! This issue can be closed now I think.

**Comment by anntzer** [comment]
The meaning of err is documented in https://invisible-island.net/xterm/ctlseqs/ctlseqs.html (search for XTSMGRAPHICS); I won't explain it better than the ref so I may just as well point you to it (err is Ps, num is Pv).
Let's keep this open for now; I think this generally points out that mplterm can be more robust when the underlying terminal doesn't handle certain codes (it should not hang, can assume 256 color registers are available per the sixel standard if the terminal fails to report that information, and skip figure resizing if the window size is not available).

**Comment by anntzer** [comment]
mplterm should now be more lenient if the underlying terminal doesn't support certain xterm-specific codes.
